### ISSUE TITLE
SUDO Usage and TRT Module 

### ISSUE THREAD

**Issue by happuji** [phaticusthiccy/WhatsAsenaDuplicated#16] opened 2021-02-07 12:15 UTC
**Plugin can't translate my study material.**
*Sir I used that a lot but translate works with some thing and with most of time that is important to work that show nothing this is the worst happen with make some bug fix and make .trt the most powerful module coz every one is use that a lot and also the information of show by the bot make a accurate and simple to use .
But at finale thing is that fix bug
Make bot for translate anything at list a any pragharph or sentence with 100 words please 
If you do that I am grateful to you 
And sorry for my English is bad ....*

**Do it simple translate anything or 100 words of sentence.**

**My love and all support can get waste**
I expect that it will be awesome .

**Useful for another person**

**Comment by phaticusthiccy** [comment] 2021-02-07 13:32
### Hi @happuji 😊 Thanks for Feedback

##

**I checked the translate module. I would like to point out that I did not encounter any errors.**
*Some special characters may be not supported*
**Moreover, its usage is as follows:**
`.trt en tr` => *From English to Turkish*
`.trt tr en` => *From Turkish to English*
`.trt en id` => *From English to Indonesian*
**...**
*Also, It takes 5-6 seconds to translate very long text*

**Comment by happuji** [comment] 2021-02-07 15:17
How see the bug label you said I can't see where it is

**Comment by happuji** [comment] 2021-02-07 15:22
Sir.



{     E.coli is a bacteria that is present inside the human body.   }
That upper one try to copy that  and translate it then tell me if it's working and I used the command for that is .trt en hi (for English to Hindi)

**Comment by happuji** [comment] 2021-02-07 15:27
My error that comes a lot times 
*-- ERROR REPORT [WHATSASENA] --*
*WhatsAsena an error has occurred!*
_This error log may include your number or the number of an opponent. Please be careful with it!_
_You can write to our Telegram group for help._
_This message should have gone to your number (saved messages)._

*Error:* ```TypeError: Cannot read property 'length' of undefined```

**Comment by happuji** [comment] 2021-02-07 15:32
And sir please tell me more about what is Sudo use ..
And how to add a link on any text I see you some time you did that

**Comment by phaticusthiccy** [comment] 2021-02-07 17:40
#### Hi, Thanks for Another Feedbacks

##

**I tried the text you gave, it's okay.** 
*Here are a few examples:*

![IMG_20210207_202240](https://user-images.githubusercontent.com/74794033/107154196-b055a580-6982-11eb-90fe-ef825959df3d.jpg)

![IMG_20210207_202254](https://user-images.githubusercontent.com/74794033/107154203-b9df0d80-6982-11eb-8cc4-23423037f5f4.jpg)

*Also you can use* `.trt` *only. It detects input language and translates the your chosen language automatically.*

##

> SUDO Mode

*The users you choose to use the bot on you without installing WhatsAsena.*
**You must use SUDO mode like this:**

```js 
// For One User
'.setvar SUDO:90xxxx,0'

// For Multiple Users
'.setvar SUDO:90xxxx,0,90xxxx,090xxxx....'

// For Only Private Message
'.setvar SUDO:90xxxx'

// For Only Private and Multiple Users
'.setvar SUDO:90xxxx,90xxxx,90xxxx....'

// For Changing Back
'.setvar SUDO:true'

/*
You must use global format. This Example numbers apply to turkey. Turkey number code is +90, so you must use without +.
You can found country codes [here](https://countrycode.org/) 
*/

##

*I dont understand your last question :/ 
If you have a problem you can rewrite here.*

**Comment by happuji** [comment] 2021-02-08 11:59
Sir ...
// For One User
'.setvar SUDO:90xxxx,0'

// For Multiple Users
'.setvar SUDO:90xxxx,0,90xxxx,0,90xxxx....'

// For Only Private Message
'.setvar SUDO:90xxxx'

// For Only Private and Multiple Users
'.setvar SUDO:90xxxx,90xxxx,90xxxx....'

// For Changing Back
'.setvar SUDO:true'



That the upper one you tell me is not understandeble  and I didn't get that my country code is +91 and tell me that if I make a sudo like


.setvar SUDO:+91xxxxxxxxxxx,0 


And then it will work in india ,

**Comment by happuji** [comment] 2021-02-08 12:05
Is your whatsapp has a violet theme 
Coz your whatsapp looks very good and I want it please

**Comment by happuji** [comment] 2021-02-08 12:07
And tell me some good whatsapp tricks and   costomization.m

**Comment by happuji** [comment] 2021-02-08 12:09
What is private use of sudo

**Comment by phaticusthiccy** [comment] 2021-02-08 23:49
### Hi @happuji 

##

*Please dont use* `+` *in SUDO. You must use without it.*
*Let me explain about private and public SUDO usage.*
*If you want the number you added to work only on your private message, please dont use* `,0` *end the number.*
*The command* `,0` *allows one to use in groups.*

##### Important ⚠️
**SUDO Users can only use the bot in the group you're in.**

##

I'm using 3th party WhatsApp application. So it wouldn't be appropriate to say this here. 
Please if you have problem under the translation name, yoi can write there. Otherwise I'll have to close.

Have a nice day.

**Comment by happuji** [comment] 2021-02-09 02:30
Thanku you sir for that precious thing

**Comment by happuji** [comment] 2021-02-09 02:33
But sir can you make command for sudo to use make use more eassy 
Like (.sudo . Give permission .approved ) like commands to sudo use easy adna removel command like (.rmsudo .remove premission ) like etc.

**Comment by phaticusthiccy** [comment] 2021-02-09 10:09
SUDO mode is set via config vars. So ı can't put any command for setting sudo much easier.

**Comment by happuji** [comment] 2021-02-10 05:25
Coz of you can t make command .so we are unable to remove person one by one at sudo ..
If I add multiple accounts in sudo then I want to remove only one. In between them ..how to do that.....
Thanks for alll

**Comment by phaticusthiccy** [comment] 2021-02-10 10:25
You can use Config Vars in Heroku. Every `.setvar` Commands editable on Heroku. All you have to do is check the config vars in heroku.

**Comment by happuji** [comment] 2021-02-10 13:34
Sir 
Sudo not working properly

**Comment by happuji** [comment] 2021-02-10 15:43
It means that I want to give a sudo then I give em but nothing works 
I used sudo for 2 weeks that nice 
But then I used on another one but this time it's.not working with each .. help please

**Comment by phaticusthiccy** [comment] 2021-02-10 16:57
### Hi @happuji 

https://status.heroku.com/incidents/2174
**Check Here.**

*Friend HEROKU is updating these proxy servers. Therefore, all changes you make on CONFIG VARS will be invalid until the update is completed.*

*It will open again when the update is complete.*
*Thanks for your understanding and patience*

Have a nice day 😊

**Comment by phaticusthiccy** [comment] 2021-02-10 18:00
> ### Hi @happuji
> https://status.heroku.com/incidents/2174
> **Check Here.**
> 
> _Friend HEROKU is updating these proxy servers. Therefore, all changes you make on CONFIG VARS will be invalid until the update is completed._
> 
> _It will open again when the update is complete._
> _Thanks for your understanding and patience_
> 
> Have a nice day 😊

**Okey, heroku updated their servers and You can continue to use Config Vars.**

*Have a nice day 😊*

**Comment by happuji** [comment] 2021-02-11 05:14
Thanks sir 😁

**Closed** 2021-02-11 08:12 UTC
Labels: Question, Usage

**Comment by happuji** [comment] 2021-02-11 14:26
Sir i am sorry to inform you that the trt module is still has bugs and that should be solved .
I use

 **The protoplasm or gelatinous material that forms the bodies of some of the lower forms of animal life.**

That upper one for translation but didn't work
Command used :
*.  .trt en hi *
 
But it then showed me that error
*-- ERROR REPORT [WHATSASENA] --*
*WhatsAsena an error has occurred!*
_This error log may include your number or the number of an opponent. Please be careful with it!_
_You can write to our Telegram group for help._
_This message should have gone to your number (saved messages)._

*Error:* ```TypeError: Cannot read property 'length' of undefined```

Help us 
 To solve it

**Comment by happuji** [comment] 2021-02-11 14:27
This sentence is also not working 
** Living substance was first observed by Corti in 1772 and was named sarcode by Dujardin in 1835.  ** 
(.trt en hi ) 

But show the only errror

**Comment by phaticusthiccy** [comment] 2021-02-12 12:52
### Hi @happuji 

##

*I checked everything and I didn't find any problems or bugs with TRT Plugin.  Its working without error.*

*I think the error is caused by another reason. Couze translate module works smoothly.*

*Can you try* `.trt` *only.*
*Also you know you have to reply to the message..*

**Comment by happuji** [comment] 2021-02-12 14:05
No .. it still has bugs it show error . Let me send the sentence .. try
that at your own ..
**Mesosome is the part inside the cell wall which helps in the synthesis of
cell wall. It's a folded structure**

Try that with comand of .trt en hi ..
And fix it ..

**Comment by phaticusthiccy** [comment] 2021-02-12 15:24
![IMG_20210212_182313](https://user-images.githubusercontent.com/74794033/107786897-79570980-6d5f-11eb-8756-b9294d75f20c.jpg)

![IMG_20210212_182242](https://user-images.githubusercontent.com/74794033/107786905-7b20cd00-6d5f-11eb-8f01-6c7c2c86208b.jpg)

*You see, its working..*

**Comment by happuji** [comment] 2021-02-12 18:56
Yes it's working now
But it has a problem that if you try to translate forwarded message it
showes error ..
It always happen to me ..

See I used .trt en hi command in that...
